### ISSUE TITLE
Timer dose only works when you press the arrows in the play filed.

### ISSUE THREAD

**Issue by Wingzzzzy** [CarsonKompon/rhythm4k#2]
I hope it can get fixed as its a bit jarring in maps where there are long pauses.

**Comment by CarsonKompon** [comment]
I'm not sure I fully understand what you're requesting. Can you clarify a bit more? :P

**Comment by Wingzzzzy** [comment]
Sure, the song timer dose not update real time it only updates when a game object (In this case a Hit Arrow) is hit.
The timer that i am talking about is the one showing how far the player is in the song.

**Comment by Wingzzzzy** [comment]
Also sorry for the first message i was still trying to wake up and as a non-native English speaker i do a lot of mistakes.

**Comment by CarsonKompon** [comment]
No worries! I totally understand now and will definitely fix this 👍

**Comment by CarsonKompon** [comment]
Also I'm not sure if you're aware but your song pack that you posted to asset party gives errors when you try to download it:
![image](https://github.com/CarsonKompon/rhythm4k/assets/5159369/55c1c0d9-1f5f-4bd9-8869-840cd6156971)

You can fix it by going to your addon settings and going to the Resources tab and making sure that all of the files on the right are highlighted properly :)
![image](https://github.com/CarsonKompon/rhythm4k/assets/5159369/ceafba66-a0f0-431a-a7b0-17fa28f5f8b0)

**Comment by Wingzzzzy** [comment]
> Also I'm not sure if you're aware but your song pack that you posted to asset party gives errors when you try to download it: ![image](https://user-images.githubusercontent.com/5159369/250358016-55c1c0d9-1f5f-4bd9-8869-840cd6156971.png)
> 
> You can fix it by going to your addon settings and going to the Resources tab and making sure that all of the files on the right are highlighted properly :) ![image](https://user-images.githubusercontent.com/5159369/250358070-ceafba66-a0f0-431a-a7b0-17fa28f5f8b0.png)

Hey thanks for the help the documentation was a bit hard to understand.

**Comment by Wingzzzzy** [comment]
I am willing to do better to understand documentaiton too.

**Comment by CarsonKompon** [comment]
Timer should count down consistently now :)
