### ISSUE TITLE
HP Drain and difficulty does not work with intiger numbers

### ISSUE THREAD

**Issue by Wingzzzzy** [CarsonKompon/rhythm4k#4]
A map that i am porting has the hp drain and difficulty of 6.5 and it seems like the engine cannot understand it. And it spews out errors but if i put it to a 5 it works.

**Comment by CarsonKompon** [comment]
HP / HP Drain is not implemented.
And I will look into non-integer difficulties :)

**Comment by CarsonKompon** [comment]
Now outdated
